apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

patches:
- patch.yaml

configMapGenerator:
- name: nginx-webapp-env
  literals:
  - ROLLOUT_TRAFFIC_PERCENTAGE=50

namespace: blue-green-example


