apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

patches:
  - target:
      kind: Service
      name: rollout-bluegreen-active
    patch: |-
      - op: replace
        path: /spec/selector
        value:
          matchLabels:
            app: rollout-bluegreen
  - target:
      kind: Service
      name: rollout-bluegreen-preview
    patch: |-
      - op: replace
        path: /spec/selector
        value:
          matchLabels:
            app: rollout-bluegreen



