# kind: Service
# apiVersion: v1
# metadata:
#   name: rollout-bluegreen-active
# spec:
#   selector:
#     app: rollout-bluegreen
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 8080
#   type: LoadBalancer
  
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: rollout-bluegreen-preview
# spec:
#   selector:
#     app: rollout-bluegreen
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 8080
#   type: LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
  labels:
    app: rollout-bluegreen
spec:
  type: LoadBalancer
  selector:
    app: rollout-bluegreen
    track: blue
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-preview
  labels:
    app: rollout-bluegreen
spec:
  type: LoadBalancer
  selector:
    app: rollout-bluegreen
    track: green
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

