apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Chart.Name }}loq-error-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: error-rate
    interval: 5m
    successCondition: result <= 0.01
    failureLimit: 3
    provider:
      datadog:
        interval: 5m
        query: |
          {{ "sum:requests.error.count{service:{{args.service-name}}} / sum:requests.request.count{service:{{args.service-name}}}" }}